<?php

// $litado = array(

//     "MARCA" => "VOLKSWAGEN", "VOLKSWAGEN", "SEAT", "OPEL",
//     "MODELO" => "PASSAT", "POLO", "IBIZA", "CORSA",
//     "COLOR" => "GRIS", "ROJO", "BLANCO", "AZUL",
//     "MATRICULA" => "..", "DDD", "DDD", "DDD"   
// );

// forma 1
$listado = array(
    "coche1" => array("VOLSKWAGEN","PASSAT","GRIS","DKFKDSLF"),
    "coche2" => array("VOLSKWAGEN","POLO","ROJO","888-777-23KF"),
    "coche3" => array("SEAT","IBIZA","BLANCO","343-43-FDF")
);

// forma 2
$listado2 = array(
    array("marca" => "VOLKSWAGEN", "modelo" => "PASSAT", "color" => "GRIS", "matricula" => "53434", "precio" => "1200€", "foto" => "volkswagen_passat.png"),
    array("marca" => "VOLKSWAGEN", "modelo" => "POLO", "color" => "AZUL", "matricula" => "3423432", "precio" => "1100€", "foto" => "volkswagen_polo.png"),
    array("marca" => "LAMBORGHINI", "modelo" => "AVENTADOR", "color" => "GRIS", "matricula" => "053-432-43G", "precio" => "1900€", "foto" => "lamborghini_aventador.png"),
    array("marca" => "HYUNDAI", "modelo" => "COUPE FX 1.6 TDI", "color" => "ROJO", "matricula" => "miMatriculaJAJA", "precio" => "4200€", "foto" => "hyundai_coupe.png"),
    array("marca" => "CYBER-TRUMP", "modelo" => "estadoUnidense", "color" => "ROJO", "matricula" => "aMarteXSiempre", "precio" => "4200€", "foto" => "ct.png")

);

?>



